# The base URL of the site.

base_url = "https://gnanaganesh.netlify.app"
theme = "anatole-zola"

compile_sass = true
highlight_code = true
build_search_index = false
generate_feed = true
highlight_theme = "base16-ocean-light"
default_language = "en"
taxonomies = [
    {name = "tags"},
]

[languages.en]
title = "Anatole"
description = "A other zola theme"
generate_feed = true


[languages.en.translations]
language_name = "English"
about = "About"
home = "Home"
tags = "Tags"
archive = "Archive"
links = "Links"
date_format = "%Y-%m-%d"
next_page = "Next Page"
last_page = "Last Page"


[extra.social]
github = ""
twitter = "w"
facebook = ""
instagram = "r"
dribbble = "t"
weibo = "y"
linkedin = ""
flickr = ""

[extra.show]
tags = true
links = true
