# The base URL of the site.

base_url = "https://gnanaganesh.netlify.app"
theme = "anatole-zola"

compile_sass = true
highlight_code = true
build_search_index = false
generate_feed = true
highlight_theme = "base16-light"
default_language = "en"
taxonomies = [
    {name = "tags"},
]

[languages.en]
title = "GG's Blog"
description = "Stories on Software engineering."
generate_feed = true


[languages.en.translations]
language_name = "English"
about = "About"
home = "Home"
tags = "Tags"
archive = "Archive"
links = "Links"
date_format = "%d-%m-%Y"
next_page = "Next Page"
last_page = "Last Page"


[extra.social]
github = "GnanaGanesh1999"
linkedin = "gnana-ganesh"

[extra.show]
tags = true
links = true

extra.default_mode = "dark"
